### ISSUE TITLE
Websockets transport stuck during the close step of a connection

### ISSUE THREAD

**Issue by akvadrako** [graphql-python/gql#130]
I am using the gql from master and experiencing an occasional deadlock. The library I'm using is calling `client.execute()` with a websocket transport. Sometimes I see an error like this: `Exception in subscribe: GeneratorExit()` and then `client.execute()` never returns.

`WebSocketTransport.execute()` does return an `ExecutionResult`, i.e. `first_result` is set. Also `AsyncClientSession.execute()` returns.

Maybe it's failing to close the connection?

**Comment by leszekhanusz** [comment]
Which version of python are you using ?

**Comment by akvadrako** [comment]
3.8.5

**Comment by leszekhanusz** [comment]
Could you try to figure out where this is stuck ? Maybe in the `await self._wait_closed.wait()` last line of websockets.py ?

And if it is possible also give a log using

```python
import logging
logging.basicConfig(level=logging.INFO)
```

**Comment by akvadrako** [comment]
I will try to find a more specific location and upload some logs. Unfortunately, it's difficult to reproduce.

**Comment by akvadrako** [comment]
Turns out it didn't take long. Here are some logs (sorry for the mess):

https://gist.github.com/b031bc6aa97ca1a15d1d363e339e3fee

Also, indeed it does get stuck on that line in `wait_closed()`. I added some print statements in `_close_coro` and `_clean_close`. Normally I see `_close_coro_` run. When it fails, I don't see it.

**Comment by leszekhanusz** [comment]
Thank you for the log, this is indeed quite strange.

Normally after we receive the `complete` message from the server, the connection should be closed cleanly by sending the `connection_terminate` message. Apparently we don't do that for the last request in the logs. The close coroutine might be stuck in the `await self._send_connection_terminate_message()` for some reason and because of that, we are stuck waiting for this coroutine to stop in the `wait_closed` method.

The connection seems to be left open as we continue to receive the keep-alive messages.

We probably need to add timeouts for some actions in the `_close_coro` and put some of these actions in try blocks to protect us in case of problems.

That being said for your use case you should really reuse the same connection instead of creating another connection for each request. This would solve the problem for you.
For that, you should use `async with client as session:` only once in the code and use `session.execute` for each of your requests. See the advanced usage in the README.

**Comment by akvadrako** [comment]
Thanks. A timeout sounds fine - I already have the closing timeout set to 1.

It wasn't my code that was calling this, but I did make some changes so that the connection isn't closed all the time. I have to say I don't find the API very intuitive. The caller isn't async and has no place to put a context manager. So it's a bit of a mess with creating a session using `client.__aenter__()` manually, wrapping the async methods and reconnecting the transport as needed.

**Comment by akvadrako** [comment]
> We probably need to add timeouts for some actions in the `_close_coro` and put some of these actions in try blocks to protect us in case of problems.

Did you notice I mentioned `close_coro` isn't run during the last call? At least according to the print statements I added.

**Comment by leszekhanusz** [comment]
> Did you notice I mentioned close_coro isn't run during the last call?

ohh interesting. I did not notice it indeed. Could you remove the line `if self.close_task is None:` in the `_fail` method and tell me if the problem appears again ? Thanks

**Comment by leszekhanusz** [comment]
Also if you are running `__aenter__` manually, you should take care that `__aexit__` is called. Are your sure that `__aexit__` is called and `self.transport.close()` in the `__aexit__` is called ?

**Comment by leszekhanusz** [comment]
I made a version of `websockets.py` with a lot of logs and also with some cleanup in a finally block.

It is available [here](https://github.com/leszekhanusz/gql/blob/websockets_transport_ensure_close/gql/transport/websockets.py)

Could you please rerun your program with it and provide me with logs again ? Is the problem still there ? That would be very useful to pinpoint the problem.

**Comment by akvadrako** [comment]
> Could you please rerun your program with it and provide me with logs again ? Is the problem still there ? That would be very useful to pinpoint the problem.

I have run the old version of my program with your branch. The logs are at https://gist.github.com/akvadrako/786844c6170c88c58e9196e7aa8227e3

> Also if you are running `__aenter__` manually, you should take care that `__aexit__` is called. Are your sure that `__aexit__` is called and `self.transport.close()` in the `__aexit__` is called ?

For the new version, I do call `__aexit__` after failures.

**Comment by leszekhanusz** [comment]
OK Thanks for your help, I found the race condition.

Please try the new `websockets.py` available [here](https://github.com/leszekhanusz/gql/blob/websockets_transport_ensure_close/gql/transport/websockets.py)

It should solve the problem. I'll wait for your feedback and create a PR if everything is OK for you.

For reference, what happens in a normal close is the following:
 - close is called by the user
 - fail is called by close to start the _close_coro task which is saved in the self.closed_task property
 - during the cleanup, another _fail is called inside the _receive_data_loop task when the connection is closed
 - this second _fail call is ignored because a closed_task is already running
 - at the end of _close_coro, the self.closed_task is reset to None

What happens in the race condition:
 - the second _fail actually runs after the _close_coro task is started
 - so instead of being ignored, this _fail trigger the creation of another _close_coro
 - but this time, self.websocket is None, so it does nothing
 - and the self.closed_task property is not reset to None which will prevent any other _close_coro to start

**Comment by akvadrako** [comment]
I have been testing your new code for 30 minutes or so. Seems to be working :)

**Comment by leszekhanusz** [comment]
This is now fixed in version 3.0.0a2
