### ISSUE TITLE
Version v3.0.0a2 is not published on pypi

### ISSUE THREAD

**Issue by leszekhanusz** [graphql-python/gql#143]
Since the switch from travis to GitHub actions the deploy to pypi did not work.

This is a credentials problem, currently waiting for an answer.

**Comment by KingDarBoja** [comment]
We are missing the secret credentials which is managed by @Cito or @syrusakbary

**Comment by Cito** [comment]
@KingDarBoja @leszekhanusz For the automatic deployment to work with GitHub actions you need to store the PyPI API token as a GitHub repository secret. It had been stored as a secret in Travis before.

The PyPI maintainers for gql are currently @syrusakbary and @mvanlonden, they should have access to the existing PyPI API token for the Project gql and can create new tokens (I recommend creating a new one). They must store this API token as a GitHub secret in the settings for this repository so that it can be used by the GitHub action. Or alternatively, they should add one of us as PyPI maintainer so that we can create API tokens as well.

**Comment by leszekhanusz** [comment]
Thanks to @syrusakbary I am now maintainer of gql on pypi.
I created a token on pypi, set it as a secret on GitHub (in pypi_password) and restarted the GitHub actions tests.
Now the deploy worked and the version is published on pypi.

**Comment by siedentop** [comment]
@leszekhanusz Are you sure it is published? 

On https://pypi.org/project/gql/ it still shows me *2.0.0* as the latest version. Maybe the pre-release is hidden in the web view, but I cannot find any indication that it exists. 

Apologies if I am wrong and it is indeed published.

**Comment by Cito** [comment]
@siedentop You need to click on "release history" to view the pre-releases.
