### ISSUE TITLE
Fix asyncio.wait DeprecationWarning on python 3.9

### ISSUE THREAD

**Issue by leszekhanusz** [graphql-python/gql#161]
Executing the tests with tox on python 3.9 will generate the following `DeprecationWarning`:

```
tests/test_async_client_validation.py: 6 tests with warnings
tests/test_phoenix_channel_exceptions.py: 1 test with warning
tests/test_websocket_exceptions.py: 14 tests with warnings
tests/test_websocket_query.py: 2 tests with warnings
tests/test_websocket_subscription.py: 2 tests with warnings
  /home/leszek/git_repos/gql/.tox/py39-dev/lib/python3.9/site-packages/websockets/server.py:712: DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal in Python 3.11.
    await asyncio.wait(
```

See Python issue [34790](https://bugs.python.org/issue34790)

**Comment by leszekhanusz** [comment]
This is apparently fixed in websockets master.
See issue [websockets #762](https://github.com/aaugustin/websockets/issues/762)
We will need to wait for the next release of websockets

**Comment by aaugustin** [comment]
OK, thanks for the clarification. Python 3.9 was released less than a month ago, so it's not like the issue lingered for a year.

One of the rare positive side effects of the lockdown is that I tend to have more time for open-source than I would otherwise have. I'll see what I can do.

Making a release would be faster than typing this comment -- `git tag 8.2 && git push --tags`. However, it requires some availability in case something goes wrong. That's why I usually take time to review what happened since the last release. In this case, a large refactoring happened.
