### ISSUE TITLE
Usability and Self-contained-ness of DSL module in v2.x

### ISSUE THREAD

**Issue by Datoclement** [graphql-python/gql#282]
(Not sure this is a place to ask these kinds of questions) 

My current project with Graphene needs graphql-core==2.3.2 and therefore I can only use v2.x of gql library. I would like to use the dynamic query construction in dsl module. I am not sure whether this part of functionality is self-contained in v2.x. I tried to find doc for v2.x but cannot find it. And unlike other functionality, there is neither demo code on dsl in v2.x. 

My question is: Is dsl a completed feature in v2.x?

Edit: I am currently looking at the v3 doc to try to understand dsl in v2 (I suppose they would be similar?) but I want to be sure that the code is at least tested and avoid unexpected behaviors.

**Comment by leszekhanusz** [comment]
V2.x is not maintained anymore.

At some point, [there was a small example in the README.md](https://github.com/graphql-python/gql/tree/dd287b39716dee1d84ab6c3d2b8d9260b86994e6#compose-graphql-queries-dynamically-with-the-dsl-module)

There was a lot of modifications in the DSL code since then:
 - we now provide a schema instead of a client in `DSLSchema` and now we use the `dsl_gql` function with the `DSLQuery`, `DSLMutation` and `DSLSubscription` classes (#169). With v2.x you call the `query` and `mutate` methods of `DSLSchema` directly
 - fragments are supported (#235)
 - we can serialize complex arguments in inputs (#255)
 - we can add variables (#210)

There were also a few bugs fixed:
- #132 
- #151

If you don't need those features and don't have recursive queries, then it should work correctly.
