### ISSUE TITLE
creating a query using DSL

### ISSUE THREAD

**Issue by mselgamal** [graphql-python/gql#315]
Hi,

i have the following query

"query {
   alertSearch(in: {cql_query: "do this then that}) {
	    status
	    reason
   }
}"

i'm trying to use DSL to construct the query, is there an example for how to include Input types ? "in" is an input type in the schema

any help is appreciated, thanks

**Comment by leszekhanusz** [comment]
You just have to call the field with your arguments. [See the documentation](https://gql.readthedocs.io/en/stable/advanced/dsl_module.html#arguments)
gql will serialize into the the query even complex arguments in lists and/or dicts.

[Here is a more complex example in test_dsl.py](https://github.com/graphql-python/gql/blob/f0790aed0e407d0d3fe7ebd28c888432324bccf3/tests/starwars/test_dsl.py#L157). It uses variables but should also work providing the values directly instead of using variables.

**Comment by leszekhanusz** [comment]
I just noticed that your argument is "in" which is a reserved keyword in python, so it is a bit more complicated to add it.
See Issue #308 

We should probably add a note about that in the documentation.

**Comment by leszekhanusz** [comment]
A little note was now added in the documentation in #317
