### ISSUE TITLE
Client.validate() with fetch_schema_from_transport=True

### ISSUE THREAD

**Issue by Dzeri96** [graphql-python/gql#346]
**Describe the bug**
After initializing a client with the `fetch_schema_from_transport` set to `True`, I was hoping on writing some queries and then always validating them in my test suite.
Unfortunately, it seems like calling `validate()` is only possible with a manually set schema, as I'm getting the error
```
Cannot validate the document locally, you need to pass a schema.
```

In my case, it's important to only fetch the schema and validate the query instead of executing it, as the API I'm hitting has a monthly request limit.

**To Reproduce**

1.  Instantiate a `Client` with `fetch_schema_from_transport` set to `True`
2. Write a query
3. Try to validate it by calling `client.validate(query)`

**Expected behavior**
The schema is fetched from the server and the validation of the query is performed against it.

**System info (please complete the following information):**
 - OS: MacOS 12.3.1
 - Python version: 3.8.12
 - gql version: 3.4.0
 - graphql-core version: 3.2.1

**Comment by leszekhanusz** [comment]
Please check the [schema validation documentation](https://gql.readthedocs.io/en/stable/usage/validation.html).

Remarks:
- you don't need to call `client.validate` yourself because gql will always validate all the queries locally if a schema is present
- for performance reasons, gql will fetch the schema only after the first connection to the backend. Creating a client is not enough, you have to make a session:

```python
client = Client(url="...", fetch_schema_from_transport=True)

# We don't have the schema here

with client as session:
    pass

# Now we have a client.schema
```

- if you want to limit the number of requests to the backend, then don't use an introspection query but instead download the schema in a file as described in the docs, the introspection query can be quite big
