### ISSUE TITLE
State of the project?

### ISSUE THREAD

**Issue by guettli** [graphql-python/gql#50]
Please tell us the current state of the project in the README.

At the moment it looks dead.

Which GraphQL client library do you recommend?

**Comment by Cito** [comment]
Yes, unfortunately this project has been abandoned.

It would be nice if anybody somebody wants to take over, revive it and act as maintainer. I'm willing to support you in making this compatible with newer graphql-core versions.

The original author and maintainer was @syrusakbary, who would need to hand over maintainer rights on PyPI so that new releases can be published.

**Comment by guettli** [comment]
I asked on stackoverflow which graph-ql lib could be used for python: https://softwarerecs.stackexchange.com/questions/70972/graphql-client-library-for-python

The answer was: this: https://github.com/graphql-python/gql-next

**Comment by Cito** [comment]
gql-next is actually the version that uses graphql-core-next, instead of the old graphql-core.  The project owner of gql-next on PyPI is also @syrusakbary, so similar problem.

Also, graphql-core-next is now released as graphql-core v3. So gql-next should be actually released as gql v3 as well to avoid confusion.

**Comment by mcouthon** [comment]
gql-next doesn't seem to be maintained as well (no updates since May 19'). I wonder if there's no actively maintained python client for GraphQL.

**Comment by ar-ms** [comment]
Hello! As another example, I'm currently using [sgqlc](https://github.com/profusion/sgqlc), that offers code generation and type inference on the query result. It is also well [documented](https://sgqlc.readthedocs.io/en/latest/).

**Comment by Cito** [comment]
Update: Syrus has now added Mel as maintainer on PyPI, so we will be able to publish patch releases again. Please give us some time to get this project back on track. I also want to merge this with gql-next.

**Comment by Cito** [comment]
Update: I have now discarded the idea to merge this with gql-next. It was based on the wrong assumption that gql-next is essentially the same as gql, just using core-next instead of core. However, gql-next is also using a very different approach. Also, I noticed that this project needs a maintainer that can do a bit more than just releasing patches and bugfixes. There are larger open issues and pull requests that need more time to investigate than I have. So if anybody wants to step up and help maintaining this library, please come forward.
