### ISSUE TITLE
Create separate documentation using Sphinx

### ISSUE THREAD

**Issue by Cito** [graphql-python/gql#89]
We should create separate documentation using Sphinx, since the README is getting too large.

The documentation can then be made availabel online as GitHub pages deployed with an GitHub action, or via ReadTheDocs. RTD has the advantage that it can create versioned docs if we need that.

**Comment by captaincoordinates** [comment]
Versioned docs would be a major benefit because "the following documentation describes the current version which is currently only available as a pre-rel[e]ase". I don't want to risk using the alpha version in my application and I wasted time trying to understand why I could not import from gql.transport.aiohttp (it didn't exist in v2)
